// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20251124213705_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("API.Models.Chamado", b =>
                {
                    b.Property<string>("ChamadoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.HasKey("ChamadoId");

                    b.ToTable("Chamados");

                    b.HasData(
                        new
                        {
                            ChamadoId = "6a8b3e4d-5e4e-4f7e-bdc9-9181e456ad0e",
                            CriadoEm = new DateTime(2025, 12, 1, 18, 37, 5, 519, DateTimeKind.Local).AddTicks(1383),
                            Descricao = "Formatar computador",
                            Status = "Aberto"
                        },
                        new
                        {
                            ChamadoId = "2f1b7dc1-3b9a-4e1a-a389-7f5d2f1c8f3e",
                            CriadoEm = new DateTime(2025, 11, 27, 18, 37, 5, 519, DateTimeKind.Local).AddTicks(1390),
                            Descricao = "Trocar tinta da impressora",
                            Status = "Aberto"
                        },
                        new
                        {
                            ChamadoId = "e5d4a7b9-1f9e-4c4a-ae3b-5b7c1a9d2e3f",
                            CriadoEm = new DateTime(2025, 12, 8, 18, 37, 5, 519, DateTimeKind.Local).AddTicks(1430),
                            Descricao = "Trocar teclado",
                            Status = "Aberto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
